# Generated by Django 5.1.5 on 2025-04-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem'),
    ]

    operations = [
    ]
